alias ssh := enter

default:
  just --list --unsorted

init *flags:
    terraform init {{flags}}

plan *flags:
    terraform plan {{flags}}

apply *flags:
    terraform apply {{flags}}

destroy *flags:
    terraform destroy {{flags}}

enter:
    aws ecs execute-command --cluster ambro-cluster --task $(just _taskid) --container twisted-app --interactive --command "bash"

_taskid:
    #!/usr/bin/env sh
    TASK=$(aws ecs list-tasks --cluster ambro-cluster | jq '.taskArns[0]' | cut -d "/" -f 3 | tr -d '"')
    echo $TASK

ip:
    aws ec2 describe-network-interfaces --network-interface-ids eni-0ecab1a115b2a0d56 | | jq ".NetworkInterfaces[].Association.PublicIp"


details:
    aws ecs describe-tasks --cluster ambro-cluster --tasks $(just _taskid)




