import os

SLACK_SIGNING_SECRET = os.environ['SLACK_SIGNING_SECRET']
SLACK_BOT_TOKEN = os.environ['SLACK_BOT_TOKEN'] 
SLACK_APP_TOKEN = os.environ['SLACK_APP_TOKEN']
TWIST_OAUTH_TOKEN = os.environ['TWIST_OAUTH_TOKEN']
