name: Deploy new app image into ECS

on:
  - push:
      branches: ["main"]
  
  - workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
    # Setup environment
    - name: "Checkout repo"
      uses: actions/checkout@v3
    - name: "Install just"
      uses: extractions/setup-just@v1
    - name: "Install terraform"
      uses: hashicorp/setup-terraform@v2

    # Initialize services (docker, terraform)
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1


    # Initialize terraform
    - name: Initialize terraform with remote state
      run: just deployment/infra/init
      

    # Deploy new app version
    - name: "Update the app Docker image"
      run: just app/updateimage

    - id: deploy
      name: "Deploy new app version into AWS ECS"
      run: just deployment/infra/apply
    - run: echo ${{ steps.deploy.outputs.stdout }}
    - run: echo ${{ steps.deploy.outputs.stderr }}
    - run: echo ${{ steps.deploy.outputs.exitcode }}
