name: Deploy new app image into ECS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
    # Setup environment
    - name: "Checkout repo"
      uses: actions/checkout@v3
    - name: "Install just"
      uses: extractions/setup-just@v1
    - name: "Install terraform"
      uses: hashicorp/setup-terraform@v2

    # Initialize services (docker, terraform)
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Initialize terraform
    - name: Initialize terraform with remote state
      run: just deployment/infra/init
      

    # Deploy new app version
    - name: "Update the app Docker image"
      run: just app/updateimage
    - name: "Deploy new app version into AWS ECS"
      run: just deployment/infra/apply
  